import DocsSection from "../DocsSection";

export default function DataLayerSection() {
  return (
    <DocsSection
      id="data-layer"
      number="T07"
      type="technical"
      eyebrow="Data Layer"
      title="Data sources, storage, and privacy"
      subtitle="Marketrix is a structured-data-first platform. All data flows from user input — not scraped from external sources. This ensures quality, consent, and auditability."
    >
      {/* Data sources */}
      <div className="dl-block">
        <h3 className="dl-heading">Data Sources</h3>
        <div className="dl-cards">
          <div className="dl-card">
            <h4 className="dl-card-title">Founder Brief Submissions</h4>
            <p className="dl-card-desc">Structured form data: startup name, industry, stage, geography, budget, goals, problems, competitors. Stored in <code>startup_requirements</code> table as JSONB fields.</p>
            <div className="dl-card-tags">
              <span className="tag">User-submitted</span>
              <span className="tag tag-emerald">Primary source</span>
            </div>
          </div>
          <div className="dl-card">
            <h4 className="dl-card-title">Analyst Reports & Profiles</h4>
            <p className="dl-card-desc">Analyst-authored reports (metadata + file key in S3), expertise tags, bio, verified status. Profile data in <code>users</code> table; files in AWS S3.</p>
            <div className="dl-card-tags">
              <span className="tag">Analyst-submitted</span>
              <span className="tag tag-gold">Secondary source</span>
            </div>
          </div>
          <div className="dl-card">
            <h4 className="dl-card-title">AI-Generated Metadata</h4>
            <p className="dl-card-desc">Brief parsing results, audience segments, recommendation explanations — all generated by Claude Sonnet and stored in <code>metadata JSONB</code> + <code>audience_segments</code> tables.</p>
            <div className="dl-card-tags">
              <span className="tag">AI-generated</span>
              <span className="tag tag-coral">Derived</span>
            </div>
          </div>
          <div className="dl-card">
            <h4 className="dl-card-title">Vector Embeddings</h4>
            <p className="dl-card-desc">1536-dimensional float vectors for each submitted brief, stored in <code>brief_embeddings</code> table using PostgreSQL pgvector type. HNSW indexed for ANN search.</p>
            <div className="dl-card-tags">
              <span className="tag">AI-generated</span>
              <span className="tag tag-emerald">Search index</span>
            </div>
          </div>
        </div>
      </div>

      {/* Schema overview */}
      <div className="dl-block">
        <h3 className="dl-heading">Key Tables</h3>
        <div className="dl-table-list">
          {[
            { table: "users", rows: "Email, password hash, role, status, bio, expertise tags, avatar URL" },
            { table: "startup_requirements", rows: "Founder ID, name, industry, stage, geography, budget, goals, problems, competitors, metadata (JSONB), status" },
            { table: "audience_segments", rows: "Requirement ID, name, tagline, demographics, psychographics, behavioral signals, channels, viability score, rationale" },
            { table: "brief_embeddings", rows: "Requirement ID, embedding vector(1536), HNSW index" },
            { table: "strategist_embeddings", rows: "User ID, embedding vector(1536), HNSW index (expert matching)" },
            { table: "recommendations", rows: "Requirement ID, type (CHANNEL/STRATEGIST/REPORT), target ID, score, explanation" },
            { table: "reports", rows: "Analyst ID, title, description, price, tier, tags, file key (S3), preview text, purchase count, status" },
            { table: "transactions", rows: "User ID, type, amount, currency, Stripe payment ID, status" },
          ].map((t, i) => (
            <div key={i} className="dl-table-row">
              <code className="dl-table-name">{t.table}</code>
              <span className="dl-table-desc">{t.rows}</span>
            </div>
          ))}
        </div>
      </div>

      {/* Privacy */}
      <div className="dl-block">
        <h3 className="dl-heading">Privacy & Data Handling</h3>
        <div className="dl-privacy-items">
          {[
            "Passwords are never stored in plaintext — bcrypt hashing enforced by Spring Security",
            "JWT tokens are stateless; refresh tokens are persisted with expiry and can be revoked",
            "Brief data is owned by the submitting founder — analysts cannot access raw brief content",
            "S3 report files are served via presigned URLs with time-limited expiry (not public URLs)",
            "AI providers (Anthropic, OpenAI) process data under their standard data processing agreements",
            "No external web scraping — all data originates from authenticated user submissions",
            "Stripe handles all payment card data — Marketrix never stores card numbers",
          ].map((item, i) => (
            <div key={i} className="dl-privacy-item">
              <span className="dl-privacy-icon">🔒</span>
              <span className="dl-privacy-text">{item}</span>
            </div>
          ))}
        </div>
      </div>

      <style>{`
        .dl-block { margin-bottom: 32px; }
        .dl-heading {
          font-family: var(--font-jetbrains), monospace;
          font-size: 0.7rem;
          font-weight: 700;
          text-transform: uppercase;
          letter-spacing: 0.12em;
          color: var(--ink-muted);
          margin: 0 0 14px;
        }
        .dl-cards {
          display: grid;
          grid-template-columns: repeat(2, 1fr);
          gap: 12px;
        }
        @media (max-width: 640px) { .dl-cards { grid-template-columns: 1fr; } }
        .dl-card {
          padding: 20px;
          border-radius: 12px;
          border: 1px solid var(--line-medium);
          background: var(--bg-surface);
          display: flex;
          flex-direction: column;
          gap: 8px;
        }
        .dl-card-title {
          font-size: 0.9rem;
          font-weight: 700;
          color: var(--ink);
          margin: 0;
          font-family: var(--font-dm-sans), system-ui, sans-serif;
        }
        .dl-card-desc {
          font-size: 0.82rem;
          color: var(--ink-soft);
          line-height: 1.6;
          margin: 0;
        }
        .dl-card-desc code {
          font-family: var(--font-jetbrains), monospace;
          font-size: 0.75rem;
          color: var(--emerald);
          background: var(--emerald-surface);
          padding: 1px 5px;
          border-radius: 3px;
        }
        .dl-card-tags { display: flex; gap: 6px; flex-wrap: wrap; }
        .dl-table-list { display: flex; flex-direction: column; gap: 0; }
        .dl-table-row {
          display: grid;
          grid-template-columns: 200px 1fr;
          gap: 16px;
          padding: 10px 0;
          border-bottom: 1px solid var(--line-soft);
          align-items: start;
        }
        .dl-table-row:last-child { border-bottom: none; }
        @media (max-width: 540px) { .dl-table-row { grid-template-columns: 1fr; gap: 4px; } }
        .dl-table-name {
          font-family: var(--font-jetbrains), monospace;
          font-size: 0.78rem;
          color: var(--gold);
          background: var(--gold-surface);
          border: 1px solid var(--gold-border);
          padding: 2px 8px;
          border-radius: 4px;
          align-self: flex-start;
        }
        .dl-table-desc {
          font-size: 0.82rem;
          color: var(--ink-muted);
          line-height: 1.5;
        }
        .dl-privacy-items { display: flex; flex-direction: column; gap: 8px; }
        .dl-privacy-item {
          display: flex;
          gap: 10px;
          align-items: flex-start;
          padding: 10px 0;
          border-bottom: 1px solid var(--line-soft);
        }
        .dl-privacy-item:last-child { border-bottom: none; }
        .dl-privacy-icon { font-size: 0.9rem; flex-shrink: 0; margin-top: 1px; }
        .dl-privacy-text {
          font-size: 0.87rem;
          color: var(--ink-soft);
          line-height: 1.55;
        }
      `}</style>
    </DocsSection>
  );
}
