spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/marketrix
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  flyway:
    clean-disabled: false

logging:
  level:
    com.example.marketrix: DEBUG
    org.springframework.security: DEBUG

cors:
  allowed-origins: http://localhost:3000
